# Generated by Django 4.2 on 2023-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('picture', models.URLField()),
            ],
        ),
    ]
