# Generated by Django 4.2 on 2023-04-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_jersey_jersey_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dry_cleaned', models.BooleanField()),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jersey')),
            ],
        ),
    ]
