# Generated by Django 4.2 on 2023-04-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cleaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateField(verbose_name='cleaning date'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='hats',
            field=models.ManyToManyField(to='main_app.hat'),
        ),
    ]
