# Generated by Django 4.2 on 2023-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_hat_alter_cleaning_date_jersey_hats'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='picture',
            field=models.URLField(default='placholder.com'),
            preserve_default=False,
        ),
    ]
